/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iMetaStoreSol from "./IMetaStore.sol";
export { IDB3MetaStore__factory } from "./IDB3MetaStore__factory";
