/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iMetaStoreSol from "./IMetaStore.sol";
export type { iMetaStoreSol };
export type { IDB3MetaStore } from "./IDB3MetaStore";
