/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as db3TokenSol from "./DB3Token.sol";
export type { db3TokenSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DB3MetaStore } from "./DB3MetaStore";
export type { DB3Rollup } from "./DB3Rollup";
