/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "DB3MetaStore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DB3MetaStore__factory>;
    getContractFactory(
      name: "DB3Rollup",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DB3Rollup__factory>;
    getContractFactory(
      name: "Db3Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Db3Token__factory>;
    getContractFactory(
      name: "IDB3MetaStore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDB3MetaStore__factory>;
    getContractFactory(
      name: "IDB3MetaStore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDB3MetaStore__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "DB3MetaStore",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DB3MetaStore>;
    getContractAt(
      name: "DB3Rollup",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DB3Rollup>;
    getContractAt(
      name: "Db3Token",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Db3Token>;
    getContractAt(
      name: "IDB3MetaStore",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDB3MetaStore>;
    getContractAt(
      name: "IDB3MetaStore",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDB3MetaStore>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
